# this_file: external/int_folders/d361/src/d361/utils/__init__.py
"""
Utils package - Common utilities and infrastructure components.

This package contains shared utilities used across the d361 library,
including logging, performance optimization, and helper functions.
"""

from .dependency_injection import (
    CircularDependencyError,
    ServiceContainer,
    ServiceDescriptor,
    ServiceError,
    ServiceLifecycle,
    ServiceNotFoundError,
    ServiceRegistrationError,
    ServiceScope,
    get_container,
    injectable,
    register_scoped,
    register_singleton,
    register_transient,
    resolve,
    set_container,
)
from .logging import (
    LogContext,
    LogFormat,
    LoggingConfig,
    LoggingManager,
    LogHandlerConfig,
    LogLevel,
    clear_log_context,
    get_logger,
    get_logging_manager,
    set_correlation_id,
    set_request_id,
    set_user_id,
    setup_development_logging,
    setup_logging,
    setup_production_logging,
)
from .performance import (
    AsyncCache,
    BatchConfig,
    BatchProcessor,
    BatchStrategy,
    CacheConfig,
    CacheStrategy,
    PerformanceMetrics,
    PerformanceOptimizer,
    async_cache,
    batch_processor,
    get_optimizer,
    performance_monitor,
    set_optimizer,
)
from .validation import (
    MigrationHelper,
    ValidatedBaseModel,
    ValidationException,
    ValidationHelper,
    validate_api_token_field,
    validate_email_field,
    validate_function_inputs,
    validate_slug_field,
    validate_url_field,
)

__all__ = [
    "AsyncCache",
    "BatchConfig",
    "BatchProcessor",
    "BatchStrategy",
    "CacheConfig",
    # Performance optimization
    "CacheStrategy",
    "CircularDependencyError",
    "LogContext",
    "LogFormat",
    "LogHandlerConfig",
    # Logging system
    "LogLevel",
    "LoggingConfig",
    "LoggingManager",
    "MigrationHelper",
    "PerformanceMetrics",
    "PerformanceOptimizer",
    "ServiceContainer",
    "ServiceDescriptor",
    "ServiceError",
    # Dependency injection system
    "ServiceLifecycle",
    "ServiceNotFoundError",
    "ServiceRegistrationError",
    "ServiceScope",
    "ValidatedBaseModel",
    # Validation and migration
    "ValidationException",
    "ValidationHelper",
    "async_cache",
    "batch_processor",
    "clear_log_context",
    "get_container",
    "get_logger",
    "get_logging_manager",
    "get_optimizer",
    "injectable",
    "performance_monitor",
    "register_scoped",
    "register_singleton",
    "register_transient",
    "resolve",
    "set_container",
    "set_correlation_id",
    "set_optimizer",
    "set_request_id",
    "set_user_id",
    "setup_development_logging",
    "setup_logging",
    "setup_production_logging",
    "validate_api_token_field",
    "validate_email_field",
    "validate_function_inputs",
    "validate_slug_field",
    "validate_url_field",
]
